[project]
name = "websockets"
version = "0.1.0"
description = "A websockets implementation in Python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.12.5",
    "pytest>=9.0.1",
]
